# Linear Algebra Recap

### A quick recaap of all the concepts learned within these 11 days in Linear Algebra

In [5]:
!pip install sympy
import numpy as np 
import pandas as pd
import scipy.linalg as la
import sympy as sp



[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: C:\Users\ASUS\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.8/6.3 MB 2.2 MB/s eta 0:00:03
   -------- ------------------------------- 1.3/6.3 MB 2.3 MB/s eta 0:00:03
   --------- ------------------------------ 1.6/6.3 MB 2.1 MB/s eta 0:00:03
   -------------- ------------------------- 2.4/6.3 MB 2.3 MB/s eta 0:00:02
   ------------------ --------------------- 2.9/6.3 MB 2.4 MB/s eta 0:00:02
   ------------------- -------------------- 3.1/6.3 MB 2.2 MB/s eta 0:00:02
   --------------------- ------------------ 3.4/6.3 MB 2.2 MB/s eta 0:00:02
   ----------------------- ---------------- 3.7/6.3 MB 2.1 MB/s eta 0:00:02
   ------------------------ --------------- 3.9/6.3 MB 1.9 MB/s eta 0:00:02
   -------------------------- ------------- 4.2/6.3 MB 1.8 MB/s eta 0:00:02
   ---------------------------- -

In [7]:
#Matrix Operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

# Matrix addition, multiplication, transpose
add_AB = A + B
mul_AB = A @ B
A_T = A.T

print("Matrix Addition:\n", add_AB)
print()
print("Matrix Multiplication:\n", mul_AB)
print()
print("Transpose of A:\n", A_T)
print()

#Rank, Null Space
rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)
print()

#Eigenvalues & PCA

eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:\n", eigvals)
print("Eigenvectors:\n", eigvecs)
print()

# Cholesky Decomposition

A = np.array([[4, 2], [2, 3]])
L = np.linalg.cholesky(A)
print("Cholesky Decomposition L:\n", L)
print()

#LU Decomposition

P, L, U = la.lu(A)
print("L:\n", L)
print("U:\n", U)
print()

#QR decomposition

Q, R = np.linalg.qr(A)
print("Q:\n", Q)
print("R:\n", R)
print()

#Singular Value Decomposition (SVD)

U, S, VT = np.linalg.svd(A)
print("U:\n", U)
print("Singular Values:\n", S)
print("VT:\n", VT)
print()

# Loss Functions- Mean Squared Error (MSE) 

y = np.array([3, -0.5, 2, 7])
y_pred = np.array([2.5, 0.0, 2, 8])
mse = np.mean((y - y_pred)**2)
print("MSE:", mse)

#Gradients And Jacobians

x, y = sp.symbols('x y')
f = x**2 + y**2
grad_f = [sp.diff(f, var) for var in (x, y)]
grad_f


Matrix Addition:
 [[3 2]
 [4 7]]

Matrix Multiplication:
 [[ 4  6]
 [10 12]]

Transpose of A:
 [[1 3]
 [2 4]]

Rank of A: 2

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Cholesky Decomposition L:
 [[2.         0.        ]
 [1.         1.41421356]]

L:
 [[1.  0. ]
 [0.5 1. ]]
U:
 [[4. 2.]
 [0. 2.]]

Q:
 [[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
R:
 [[-4.47213595 -3.13049517]
 [ 0.          1.78885438]]

U:
 [[-0.78820544 -0.61541221]
 [-0.61541221  0.78820544]]
Singular Values:
 [5.56155281 1.43844719]
VT:
 [[-0.78820544 -0.61541221]
 [-0.61541221  0.78820544]]

MSE: 0.375


[2*x, 2*y]