In [1]:
import numpy as np

## Vector Norms: 

* L1 (Manhattan Distance)
* L2 (Euclidean Distance)
* Lp (Generalization norm)

In [3]:
"""
Consider a vector V with components v1,v2,v3.........vn

V = (v1,v2,v3......vn)
"""

V=np.array([2,14,5,6,8])


#L1 norm -> Sum of absolute vallues of all the components

L1 = np.sum(np.abs(V)) #sum of absolute values of V

print(f" L1 Norm of {V} : {L1}")
print()


#L2 norm -> Square root of sum of squares of all components (pythagoras formula)

L2 = np.sqrt(np.sum(V**2))

print(f" L2 Norm of {V} : {L2}")
print()

#Lp norm -> generalisation norm , depends on paramter p  
#||V||_p = (sum(|Vi|^p))^(1/p)

p=2.5
Lp = np.sum(np.abs(V)**p)**(1/p)
print(f" Lp Norm of {V} : {Lp}")

 L1 Norm of [ 2 14  5  6  8] : 35

 L2 Norm of [ 2 14  5  6  8] : 18.027756377319946

 Lp Norm of [ 2 14  5  6  8] : 16.247889447678435


## Vector Spaces and Subspaces

In [5]:
v1 = np.array([1, 2, 3])
v2 = np.array([2, 4, 6])  
v3 = np.array([1, 0, 1])

A = np.column_stack((v1, v2, v3)) #used to stack vectors in a coumn matrix


rank = np.linalg.matrix_rank(A) # Rank = number of independent columns

print("Matrix A:\n", A)
print("Rank:", rank)
print("Independent?", rank == A.shape[1])

#independent is false because v2 is a multiple of v1, that is the two vectors are dependent on each other


Matrix A:
 [[1 2 1]
 [2 4 0]
 [3 6 1]]
Rank: 2
Independent? False


## Basis 

In [8]:
B = np.column_stack(([1,2,3], [2,4,6], [0,0,1]))
print("Matrix B:\n", B)
print()

rank = np.linalg.matrix_rank(B)
print("Rank:", rank)
print()

if rank == 3:
    print("The vectors form a basis for R**3")
else:
    print(f"The vectors form a basis of a {rank}D subspcae inside R**3")
    


Matrix B:
 [[1 2 0]
 [2 4 0]
 [3 6 1]]

Rank: 2

The vectors form a basis of a 2D subspcae inside R**3


## Orthogonality

In [10]:
"""
Dot product of two vectors is 0
u.v=0
"""

u = np.array([1, -1, 0])
v = np.array([1, 1, 0])

dot = np.dot(u, v)
print("Dot product:", dot)
print()

if dot == 0:
    print("u and v are orthogonal")
else:
    print("u and v are not orthogonal")

Dot product: 0

u and v are orthogonal


## Vector Projection

In [12]:
"""
projection of u onto v -> ((u.v)/v.v)*v
"""

u = np.array([3, 4])
v = np.array([1, 2])

proj = (np.dot(u, v) / np.dot(v, v)) * v
print("Projection of u onto v:", proj)


Projection of u onto v: [2.2 4.4]


## Gram–Schmidt Orthogonalization

* v1,v2,v3....vn
* First orthogonal vector u1=v1
* subtract out the projection of v2 onto u1 :
  * u2 = v2 - projection (v2 onto u1)
* subtract out the projection of v3 onto u1 and u2 :
  * u3 = v3 - projection (v3 onto u1) - projection (v3 onto u2)
* Continue until all are orthogonal
* Normalize if you want orthonormal basis

In [13]:
def gram_schmidt(vectors):
    vectors = [np.array(v, dtype=float) for v in vectors]
    ortho = []
    
    for v in vectors:
        for u in ortho:
            v = v - (np.dot(v, u) / np.dot(u, u)) * u
        ortho.append(v)
    
    ortho_norm = [u / np.linalg.norm(u) for u in ortho] # Normalize (orthonormal basis)
    return ortho, ortho_norm

V = [[1, 1, 0], [1, 0, 1], [0, 1, 1]]
U, E = gram_schmidt(V)

print("Orthogonal basis:")
for vec in U:
    print(vec)
print()

print("\nOrthonormal basis:")
for vec in E:
    print(vec)


Orthogonal basis:
[1. 1. 0.]
[ 0.5 -0.5  1. ]
[-0.66666667  0.66666667  0.66666667]


Orthonormal basis:
[0.70710678 0.70710678 0.        ]
[ 0.40824829 -0.40824829  0.81649658]
[-0.57735027  0.57735027  0.57735027]
